if (process.env.NODE_ENV === "development") {
  module.exports = [
    { name: "dependencies_react", type: "umd" },
    { name: "dependencies_scheduler", type: "umd" },
    { name: "dependencies_react_dom", type: "umd" },
    { name: "dependencies__formatjs", type: "umd" },
    { name: "dependencies_hoist_non_react_statics", type: "umd" },
    { name: "dependencies_intl_messageformat", type: "umd" },
    { name: "dependencies_react_is", type: "umd" },
    { name: "dependencies_tslib", type: "umd" },
    { name: "dependencies_react_intl", type: "umd" },
    { name: "dependencies__babel", type: "umd" },
    { name: "dependencies_use_sync_external_store", type: "umd" },
    { name: "dependencies_react_redux", type: "umd" },
    { name: "dependencies_redux", type: "umd" },
    { name: "dependencies__redux_saga", type: "umd" },
    { name: "dependencies_redux_saga", type: "umd" },
    { name: "dependencies__remix_run", type: "umd" },
    { name: "dependencies_react_router", type: "umd" },
    { name: "dependencies_react_router_dom", type: "umd" },
    { name: "dependencies__emotion", type: "umd" },
    { name: "dependencies__linaria_core", type: "umd" },
    { name: "dependencies__linaria_react", type: "umd" },
    { name: "dependencies_regenerator_runtime", type: "umd" },
    { name: "dependencies", type: "var" },
  ];
} else {
  module.exports = [
    { name: "dependencies_react", type: "umd" },
    { name: "dependencies_scheduler", type: "umd" },
    { name: "dependencies_react_dom", type: "umd" },
    { name: "dependencies__formatjs", type: "umd" },
    { name: "dependencies_hoist_non_react_statics", type: "umd" },
    { name: "dependencies_intl_messageformat", type: "umd" },
    { name: "dependencies_react_is", type: "umd" },
    { name: "dependencies_tslib", type: "umd" },
    { name: "dependencies_react_intl", type: "umd" },
    { name: "dependencies__babel", type: "umd" },
    { name: "dependencies_use_sync_external_store", type: "umd" },
    { name: "dependencies_react_redux", type: "umd" },
    { name: "dependencies_redux", type: "umd" },
    { name: "dependencies__redux_saga", type: "umd" },
    { name: "dependencies_redux_saga", type: "umd" },
    { name: "dependencies__remix_run", type: "umd" },
    { name: "dependencies_react_router", type: "umd" },
    { name: "dependencies_react_router_dom", type: "umd" },
    { name: "dependencies__emotion", type: "umd" },
    { name: "dependencies__linaria_core", type: "umd" },
    { name: "dependencies__linaria_react", type: "umd" },
    { name: "dependencies_regenerator_runtime", type: "umd" },
    { name: "dependencies", type: "var" },
  ];
}
