name: Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - name: install @lastui/rocker dependencies
        run: npm ci --no-fund --no-audit
      - name: install @lastui/dependencies dependencies
        working-directory: dependencies
        run: npm ci --no-fund --no-audit
      - uses: actions/cache/save@v4
        with:
          path: |
            node_modules
            dependencies/node_modules
          key: cache-${{ github.sha }}-dependencies
      - name: Wait for cache to be published
        run: |
          gh extension install actions/gh-actions-cache

          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH -L 100 | cut -f 1 )
          echo "${cacheKeysForPR}"
          echo "Done"

  compile:
    name: Compile
    needs: setup
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            dependencies/node_modules
          key: cache-${{ github.sha }}-dependencies
          fail-on-cache-miss: true
      - run: npm run build:dependencies
      - run: npm run build:platform
      - run: npm run build:bootstrap
      - run: npm run postbuild
      - name: Cache workspace
        id: cache
        uses: actions/cache/save@v4
        with:
          path: |
            dependencies/dll
            platform/dll
            bootstrap/dll
          key: cache-${{ github.sha }}-dlls

  test:
    name: Test
    needs: setup
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            dependencies/node_modules
          key: cache-${{ github.sha }}-dependencies
          fail-on-cache-miss: true
      - name: Test package platform
        working-directory: platform
        run: node ../cli/index.js test
      - name: Collect coverage for platform
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          flags: unittests
          file: platform/coverage/clover.xml
      - name: Test package bootstrap
        working-directory: bootstrap
        run: node ../cli/index.js test
      - name: Collect coverage for bootstrap
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          flags: unittests
          file: bootstrap/coverage/clover.xml

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
      - uses: actions/cache/restore@v4
        with:
          path: node_modules
          key: cache-${{ github.sha }}-dependencies
          fail-on-cache-miss: true
      - run: npm run lint -- --debug
      