name: Pull Request Gating

on:
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org
          scope: "@lastui"
      - name: Install dependencies
        run: npm ci
      - name: Test platform
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "cd platform && node ../cli/index.js test"
      - name: Test bootstrap
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "cd bootstrap && node ../cli/index.js test"

