name: Pull Request Gating

on:
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Gate PR
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org
          scope: "@lastui"
      - name: Install dependencies
        run: npm ci
      - name: Compile package dependencies
        run: npm run build:dependencies
      - name: Compile package platform
        run: npm run build:platform
      - name: Compile package bootstrap
        run: npm run build:bootstrap
      - name: Test package platform
        working-directory: platform
        run: node ../cli/index.js test
      - name: Collect coverage for platform
        uses: codecov/codecov-action@v1.0.13
        with:
          file: platform/coverage/clover.xml
      - name: Test package bootstrap
        working-directory: bootstrap
        run: node ../cli/index.js test
      - name: Collect coverage for bootstrap
        uses: codecov/codecov-action@v1.0.13
        with:
          file: bootstrap/coverage/clover.xml

