name: Version bump & publish to npm

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Update version and publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: publish
        uses: pascalgn/npm-publish-action@1.3.7
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
