name: Publish to npm

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          npm install
      - name: Compile package dependencies
        run: |
          cd dependencies
          npm install
          npm run build
      - name: Compile package platform
        run: |
          cd platform
          npm run build
      - name: Compile package runtime
        run: |
          cd runtime
          npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
