name: Publish to npm

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          registry-url: https://registry.npmjs.org
          scope: "@lastui"
      - run: npm ci --no-fund --no-audit
      - run: npm run build:dependencies
      - run: npm run build:platform
      - run: npm run build:bootstrap
      - run: npm run postbuild
      - run: node ./cli/index.js --cwd=platform test
      - run: node ./cli/index.js --cwd=bootstrap test
      - name: Publish @lastui/dependencies
        continue-on-error: true
        working-directory: dependencies
        run: npm publish --fetch-retries=10 --loglevel=verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish @lastui/rocker
        continue-on-error: true
        run: npm publish --fetch-retries=10 --loglevel=verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
