name: Publish to npm

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Compile package dependencies
        working-directory: dependencies
        run: npm run build
      - name: Compile package platform
        working-directory: platform
        run: npm run build
      - name: Compile package runtime
        working-directory: runtime
        run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
