name: Publish

on:
  workflow_run:
    workflows:
      - Checks
    branches:
      - main
    types:
      - completed

jobs:

  publish:
    name: Publish to registry.npmjs.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          registry-url: https://registry.npmjs.org
          scope: "@lastui"
      - name: Wait for cache to be ready
        timeout-minutes: 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh extension install actions/gh-actions-cache
          KEY="cache-${{ github.sha }}-dlls"
          while ret=0; $(gh actions-cache list --key $KEY | grep -q $KEY) || ret=$?; [ $ret -ne 0 ] ; do
            sleep 1
          done
      - uses: actions/cache/restore@v4
        with:
          path: |
            dependencies/dll
            platform/dll
            bootstrap/dll
          key: cache-${{ github.sha }}-dlls
          restore-keys: |
            cache-${{ github.sha }}-dlls
          fail-on-cache-miss: true
      - name: Publish @lastui/dependencies
        continue-on-error: true
        working-directory: dependencies
        run: npm publish --fetch-retries=10 --loglevel=verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish @lastui/rocker
        continue-on-error: true
        run: npm publish --fetch-retries=10 --loglevel=verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
