name: Publish to registry.npmjs.org

on:
  push:
    branches:
      - main

jobs:

  publish:
    needs: test
    name: Publish to registry.npmjs.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          registry-url: https://registry.npmjs.org
          scope: "@lastui"
      - name: Restore cached workspace
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: |
            dependencies/dll
            platform/dll
            bootstrap/dll
          key: cache-${{ github.sha }}
      - name: Publish @lastui/dependencies
        continue-on-error: true
        working-directory: dependencies
        run: npm publish --fetch-retries=10 --loglevel=verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish @lastui/rocker
        continue-on-error: true
        run: npm publish --fetch-retries=10 --loglevel=verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
