name: Publish

on:
  workflow_run:
    workflows:
      - Checks
    branches:
      - main
    types:
      - completed

jobs:

  publish:
    name: Publish to registry.npmjs.org
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          registry-url: https://registry.npmjs.org
          scope: "@lastui"
      - uses: actions/cache/restore@v4
        with:
          path: |
            dependencies/index.js
            dependencies/sbom.json
            dependencies/dll
            platform/dll
            bootstrap/dll
          key: cache-${{ github.sha }}-dlls
          fail-on-cache-miss: true
      - name: Publish @lastui/dependencies
        continue-on-error: true
        working-directory: dependencies
        run: npm publish --fetch-retries=10 --loglevel=verbose --access=public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish @lastui/rocker
        continue-on-error: true
        run: npm publish --fetch-retries=10 --loglevel=verbose --access=public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
