name: Publish to npm

on:
  push:
    branches:
      - main

jobs:

  build:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Compile package dependencies
        working-directory: dependencies
        run: npm run build
      - name: Compile package platform
        working-directory: platform
        run: npm run build
      - name: Compile package bootstrap
        working-directory: bootstrap
        run: npm run build
      - name: Publish @lastui/dependencies
        working-directory: dependencies
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish @lastui/rocker
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
