name: Testing

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  build:
    name: Run Tests and Report Coverage
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          scope: "@lastui"
      - run: npm ci --no-fund --no-audit
      - run: npm run build:dependencies
      - run: cat dependencies/dll/dependencies-dev-manifest.json
      - run: cat dependencies/dll/dependencies-prod-manifest.json
      - run: npm run build:platform
      - run: npm run build:bootstrap
      - name: Test package platform
        working-directory: platform
        run: node ../cli/index.js test
      - name: Collect coverage for platform
        uses: codecov/codecov-action@v3
        with:
          file: platform/coverage/clover.xml
      - name: Test package bootstrap
        working-directory: bootstrap
        run: node ../cli/index.js test
      - name: Collect coverage for bootstrap
        uses: codecov/codecov-action@v3
        with:
          file: bootstrap/coverage/clover.xml

